### ISSUE TITLE
Api Server: Error UseBody

### ISSUE THREAD

**Issue by irfnrdh** [BayBreezy/nuxt-3-server-api#1]
![image](https://user-images.githubusercontent.com/7637012/214319557-71df9589-aa1b-44a2-8e90-f22fa868e312.png)

Fix : https://nuxt.com/docs/guide/directory-structure/server#handling-requests-with-body
`const body = await useBody(event);` to `const body = await readBody(event);`

**Comment by BayBreezy** [comment]
Thank you @irfnrdh .. I think this changed with the stable release of nuxt

**Comment by BayBreezy** [comment]
I forgot to close this 😄
